import { test, expect } from '@playwright/test';
import { JobsPage } from '../pages/JobsPage';

// What It Tests: The Jobs page loads with its nav marked current, renders
// either real listings or an honest empty state (never a blank gap), its
// search/filter controls behave correctly regardless of how many listings a
// given build actually pulled in, and its required source-attribution and
// outbound search links are real.
// Why It Matters: public/data/jobs.json is regenerated by scripts/fetch-jobs.mjs
// from live third-party boards on every build — the set of jobs is expected to
// change (sometimes to zero), so this suite avoids asserting on any specific
// listing's content and instead verifies structure and behavior.
test.describe('Jobs', () => {
  test(
    'Test_Case_14000_Jobs_Page_LoadsWithNavMarkedCurrent',
    { tag: '@smoke' },
    async ({ page }) => {
      const jobs = new JobsPage(page);
      await jobs.goto();

      await test.step('Then the heading is visible', async () => {
        await expect.soft(jobs.heading).toBeVisible();
      });

      await test.step('Then the Jobs nav link is marked as the current page', async () => {
        await expect.soft(jobs.navLink('jobs')).toHaveAttribute('aria-current', 'page');
      });
    },
  );

  test(
    'Test_Case_14001_Jobs_List_RendersCardsOrAnEmptyState',
    { tag: '@smoke' },
    async ({ page }) => {
      const jobs = new JobsPage(page);
      await jobs.goto();

      await test.step('Then either at least one job card or the empty-state message renders', async () => {
        const firstCard = jobs.jobsList.locator('.job-card').first();
        await expect.soft(firstCard.or(jobs.emptyState)).toBeVisible();
      });

      await test.step('Then the "last refreshed" label is populated once loading finishes', async () => {
        await expect.soft(jobs.updatedLabel).not.toHaveText('');
      });

      await test.step('Then every rendered card shows a Remote/Hybrid/On-site badge', async () => {
        const cards = jobs.jobsList.locator('.job-card');
        const count = await cards.count();
        for (let i = 0; i < count; i++) {
          await expect
            .soft(cards.nth(i).locator('.job-badge'))
            .toHaveText(/^(Remote|Hybrid|On-site)$/);
        }
      });
    },
  );

  test(
    'Test_Case_14002_Jobs_Search_FiltersToMatchingListingsOnly',
    { tag: '@regression' },
    async ({ page }) => {
      const jobs = new JobsPage(page);
      await jobs.goto();

      // src/jobs.js hides the search/filter controls entirely when a build
      // pulled in zero jobs — a real, expected state (see README.md#job-listings)
      // that leaves nothing for search to filter.
      test.skip(
        !(await jobs.searchInput.isVisible()),
        'No jobs fetched this build — search controls are hidden with nothing to filter.',
      );

      const cards = jobs.jobsList.locator('.job-card');

      await test.step('When searching for text that matches nothing', async () => {
        await jobs.searchInput.fill('zzz-no-such-listing-exists-zzz');
        await expect.soft(jobs.emptyState).toBeVisible();
        await expect.soft(cards).toHaveCount(0);
      });

      await test.step('Then clearing the search restores the original list', async () => {
        await jobs.searchInput.fill('');
        const firstCard = cards.first();
        await expect.soft(firstCard.or(jobs.emptyState)).toBeVisible();
      });
    },
  );

  test(
    'Test_Case_14003_Jobs_WorkTypeFilter_OnlyShowsMatchingBadges',
    { tag: '@regression' },
    async ({ page }) => {
      const jobs = new JobsPage(page);
      await jobs.goto();

      test.skip(
        !(await jobs.workTypeFilter.isVisible()),
        'No jobs fetched this build — the filter is hidden with nothing to filter.',
      );

      await test.step('When filtering to Hybrid roles only', async () => {
        await jobs.workTypeFilter.selectOption('Hybrid');
        const cards = jobs.jobsList.locator('.job-card');
        const count = await cards.count();

        if (count === 0) {
          await expect.soft(jobs.emptyState).toBeVisible();
        } else {
          for (let i = 0; i < count; i++) {
            await expect.soft(cards.nth(i).locator('.job-badge')).toHaveText('Hybrid');
          }
        }
      });
    },
  );

  test(
    'Test_Case_14005_Jobs_CountryFilter_DefaultsToUnitedStatesAndFiltersCorrectly',
    { tag: '@regression' },
    async ({ page }) => {
      const jobs = new JobsPage(page);
      await jobs.goto();

      test.skip(
        !(await jobs.countryFilter.isVisible()),
        'No jobs fetched this build — the filter is hidden with nothing to filter.',
      );

      const cards = jobs.jobsList.locator('.job-card');

      await test.step('Then the region filter defaults to United States on load', async () => {
        await expect.soft(jobs.countryFilter).toHaveValue('United States');
        const count = await cards.count();
        for (let i = 0; i < count; i++) {
          await expect.soft(cards.nth(i)).toHaveAttribute('data-country', 'United States');
        }
      });

      await test.step('Then switching to All Regions never shows fewer listings', async () => {
        const usCount = await cards.count();
        await jobs.countryFilter.selectOption('all');
        const allCount = await cards.count();
        expect.soft(allCount).toBeGreaterThanOrEqual(usCount);
      });
    },
  );

  test(
    'Test_Case_14004_Jobs_SourceLinks_PointToRealDestinations',
    { tag: '@regression' },
    async ({ page }) => {
      const jobs = new JobsPage(page);
      await jobs.goto();

      await test.step('Then the general-board attribution links are all real', async () => {
        await expect.soft(jobs.sourceLinks).toHaveCount(4);
        const hrefs = await jobs.sourceLinks.evaluateAll((links) =>
          links.map((link) => link.getAttribute('href')),
        );
        expect.soft(hrefs).toContain('https://remoteok.com/remote-qa-jobs');
        expect.soft(hrefs).toContain('https://www.arbeitnow.com/?search=QA');
        expect.soft(hrefs).toContain('https://remotive.com/remote-jobs/quality-assurance');
        expect.soft(hrefs).toContain('https://jobicy.com/remote-quality-assurance-jobs');
      });

      await test.step('Then the LinkedIn and Indeed links point to real outbound searches', async () => {
        await expect
          .soft(jobs.searchEngineLink('LinkedIn'))
          .toHaveAttribute('href', 'https://www.linkedin.com/jobs/search/?keywords=QA%20Engineer');
        await expect
          .soft(jobs.searchEngineLink('Indeed'))
          .toHaveAttribute('href', 'https://www.indeed.com/jobs?q=QA+Engineer');
        await expect.soft(jobs.searchEngineLink('LinkedIn')).toHaveAttribute('target', '_blank');
        await expect.soft(jobs.searchEngineLink('Indeed')).toHaveAttribute('target', '_blank');
      });
    },
  );
});
